version: '3'
services:
  frontend:
    container_name: frontend
    build: 
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
     - "8000:80"

  backend:
    container_name: backend
    build: .
    ports:
     - "5000:5000"

  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - data:/data
    restart: always
    ports:
      - "27017:27017"

volumes:
  data:

